language: go

go:
  - stable

services:
  - docker

env:
  - GO111MODULE=on

before_install:
  - sudo /etc/init.d/postgresql stop

install: true

before_script:
  - docker-compose -f build/docker-compose.yml up -d

script:
  - go build
  - go test -v -cover -covermode=atomic -coverprofile=tests.out ./...

after_script:
  - docker-compose -f build/docker-compose.yml down -v

after_success:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=tests.out -service travis-ci -repotoken $COVERALLS_TOKEN
