name: Pull Request
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MD: true
          VALIDATE_GO: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [lint]
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build the stack
      run: docker-compose -f build/docker-compose.yml up -d
      env:
        DEFAULT_REGION: eu-central-1
        AWS_ACCOUNT_ID: "000000000000"
        AWS_ACCESS_KEY_ID: dummy-access-key
        AWS_SECRET_ACCESS_KEY: dummy-secret-key

    - name: Install awslocal
      run: |
        pip install awscli-local

    - name: Test
      run: | 
        awslocal kinesis create-stream --stream-name test --shard-count 1
        make test

    - name: Down the stack
      if: always()
      run: docker-compose -f build/docker-compose.yml down -v
